export const ENDPOINTS_MAP = {
  'register':{
    'dev':'/user/register'
  },
  'login':{
    'dev':'/user/login'
  },
  'isLogged':{
    'dev':'/user/isLogged'
  },
  'logout':{
    'dev':'/user/logout'
  },
  'salvaPuntoInteresse':{
    'dev':'/maps/salvaPuntoInteresse'
  },
  'getPuntoInteresse':{
    'dev':'/maps/getPuntoInteresse'
  },
  'rimuoviPuntoInteresse':{
    'dev':'/maps/rimuoviPuntoInteresse'
  },
}
